<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Sandeep" failures="2" tests="8" name="TestFailedCasesRetry " time="0.104" errors="0" timestamp="2024-06-16T20:48:53 IST">
  <testcase classname="com.testng.test.TestRetry" name="test3" time="0.018">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.testng.test.TestRetry" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.testng.test.TestRetry" name="test3" time="0.001">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase classname="com.testng.test.TestRetry" name="test3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testng.test.TestRetry.test3(TestRetry.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="com.testng.test.TestRetry" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.testng.test.TestRetry" name="test4" time="0.001">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.testng.test.TestRetry" name="test4" time="0.002">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase classname="com.testng.test.TestRetry" name="test4" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testng.test.TestRetry.test4(TestRetry.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
</testsuite> <!-- TestFailedCasesRetry  -->
